INSERT INTO Profile VALUES(1,'ADMIN');
INSERT INTO Profile VALUES(2,'ORIENTADOR');
INSERT INTO Profile VALUES(3,'PESQUISADOR');
INSERT INTO Profile VALUES(4,'VETERINARIA');
INSERT INTO Profile VALUES(5,'TRATADOR');